// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYD9kbgvpSmJc342ap7lOmTG7l3DWFzWM',
    appId: '1:865790848249:android:5c83c556a42935faebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqhfjFnhSLr2-xkwkMPLuLSdDbjCc6Wc',
    appId: '1:865790848249:ios:c8ec37f06f5bc4bfebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
    iosClientId: '865790848249-p87tbjstndqc92qs3r27cai5b5ltpp1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymOccupancy',
  );
}
