// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDey9OomewDjDPkKu94Z9GtbJN7QgU5_VA',
    appId: '1:865790848249:web:ae00f6559dae9335ebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    authDomain: 'gym-occupancy-d90d0.firebaseapp.com',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Sqy-ePpAtOC6DX0J8g0qxfC8P_no_rM',
    appId: '1:865790848249:android:328340b0db98837cebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChu3e8pVQIa80OUxACbgUS8fotQbRmpHg',
    appId: '1:865790848249:ios:5adab5b46ea8f335ebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
    iosClientId: '865790848249-p87tbjstndqc92qs3r27cai5b5ltpp1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymOccupancy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChu3e8pVQIa80OUxACbgUS8fotQbRmpHg',
    appId: '1:865790848249:ios:b41985324dd3f0b1ebc628',
    messagingSenderId: '865790848249',
    projectId: 'gym-occupancy-d90d0',
    databaseURL: 'https://gym-occupancy-d90d0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gym-occupancy-d90d0.appspot.com',
    iosClientId: '865790848249-rmdrosumtaet2dqjjb83aofhe2nba38t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymOccupancy.RunnerTests',
  );
}
